// apps/demo/src/App.tsx
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from '@unvalley/cmdk-react'
import { useEffect, useState } from 'react'

type Action = {
  value: string
  label: string
  hint?: string
  keywords?: readonly string[]
}

const NAVIGATION: readonly Action[] = [
  { value: 'go-home', label: 'Go to Home', hint: 'G H' },
  { value: 'go-projects', label: 'Go to Projects', hint: 'G P' },
  { value: 'go-issues', label: 'Go to Issues', hint: 'G I', keywords: ['bugs', 'tasks'] },
  { value: 'go-settings', label: 'Go to Settings', hint: 'G S', keywords: ['prefs'] },
]

const ACTIONS: readonly Action[] = [
  { value: 'new-file', label: 'New file', hint: '⌘N', keywords: ['create'] },
  { value: 'save', label: 'Save', hint: '⌘S' },
  { value: 'duplicate', label: 'Duplicate', hint: '⌘D' },
  { value: 'delete', label: 'Delete', keywords: ['remove', 'trash'] },
]

const ACCOUNT: readonly Action[] = [
  { value: 'profile', label: 'View profile', keywords: ['me', 'account'] },
  { value: 'sign-out', label: 'Sign out', keywords: ['logout', 'exit'] },
]

export const App = () => {
  const [open, setOpen] = useState(false)
  const [log, setLog] = useState<string[]>([])

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'k' && (e.metaKey || e.ctrlKey)) {
        e.preventDefault()
        setOpen((v) => !v)
      }
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [])

  const run = (value: string) => {
    setLog((l) => [`Ran: ${value} (${new Date().toLocaleTimeString()})`, ...l].slice(0, 8))
    setOpen(false)
  }

  return (
    <div className="page">
      <header>
        <h1>cmdk demo</h1>
        <p>
          Framework-agnostic command menu — <code>@unvalley/cmdk-react</code>
        </p>
      </header>

      <section className="hero">
        <button type="button" className="trigger" onClick={() => setOpen(true)}>
          Open command menu
        </button>
        <p className="hint">
          or press <kbd>⌘</kbd> <kbd>K</kbd>
        </p>
      </section>

      <section>
        <h2>Recent activity</h2>
        {log.length === 0 ? (
          <p className="muted">Select a command — activity will appear here.</p>
        ) : (
          <ul className="log">
            {log.map((line) => (
              // biome-ignore lint/suspicious/noArrayIndexKey: log entries embed their own timestamp making them effectively unique
              <li key={line}>{line}</li>
            ))}
          </ul>
        )}
      </section>

      <CommandDialog open={open} onOpenChange={setOpen} label="Global command menu" loop>
        <CommandInput placeholder="What do you want to do?" />
        <CommandList>
          <CommandEmpty>No matching command.</CommandEmpty>
          <CommandGroup heading="Navigation">
            {NAVIGATION.map((a) => (
              <CommandItem key={a.value} value={a.value} keywords={a.keywords} onSelect={run}>
                <span>{a.label}</span>
                {a.hint && <span className="hint-mono">{a.hint}</span>}
              </CommandItem>
            ))}
          </CommandGroup>
          <CommandSeparator />
          <CommandGroup heading="Actions">
            {ACTIONS.map((a) => (
              <CommandItem key={a.value} value={a.value} keywords={a.keywords} onSelect={run}>
                <span>{a.label}</span>
                {a.hint && <span className="hint-mono">{a.hint}</span>}
              </CommandItem>
            ))}
          </CommandGroup>
          <CommandSeparator />
          <CommandGroup heading="Account">
            {ACCOUNT.map((a) => (
              <CommandItem key={a.value} value={a.value} keywords={a.keywords} onSelect={run}>
                {a.label}
              </CommandItem>
            ))}
          </CommandGroup>
        </CommandList>
      </CommandDialog>
    </div>
  )
}

// demo/vue/src/App.vue
<script setup lang="ts">
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from '@command-palette/vue'
import { onBeforeUnmount, onMounted, ref } from 'vue'

type Action = {
  value: string
  label: string
  hint?: string
  keywords?: readonly string[]
}

const frameworkLabel = '@command-palette/vue'
const open = ref(false)
const log = ref<string[]>([])

const navigation: readonly Action[] = [
  { value: 'go-home', label: 'Go to Home', hint: 'G H' },
  { value: 'go-projects', label: 'Go to Projects', hint: 'G P' },
  { value: 'go-issues', label: 'Go to Issues', hint: 'G I', keywords: ['bugs', 'tasks'] },
  { value: 'go-settings', label: 'Go to Settings', hint: 'G S', keywords: ['prefs'] },
]

const actions: readonly Action[] = [
  { value: 'new-file', label: 'New file', hint: '⌘N', keywords: ['create'] },
  { value: 'save', label: 'Save', hint: '⌘S' },
  { value: 'duplicate', label: 'Duplicate', hint: '⌘D' },
  { value: 'delete', label: 'Delete', keywords: ['remove', 'trash'] },
]

const account: readonly Action[] = [
  { value: 'profile', label: 'View profile', keywords: ['me', 'account'] },
  { value: 'sign-out', label: 'Sign out', keywords: ['logout', 'exit'] },
]

const onKeydown = (event: KeyboardEvent): void => {
  if (event.key === 'k' && (event.metaKey || event.ctrlKey)) {
    event.preventDefault()
    open.value = !open.value
  }
}

onMounted(() => {
  document.addEventListener('keydown', onKeydown)
})

onBeforeUnmount(() => {
  document.removeEventListener('keydown', onKeydown)
})

const run = (value: string): void => {
  log.value = [`Ran: ${value} (${new Date().toLocaleTimeString()})`, ...log.value].slice(0, 8)
  open.value = false
}
</script>

<template>
  <div class="page">
    <header>
      <h1>cmdk demo</h1>
      <p>
        Framework-agnostic command menu —
        <code>{{ frameworkLabel }}</code>
      </p>
    </header>

    <section class="hero">
      <button type="button" class="trigger" @click="open = true">Open command menu</button>
      <p class="hint">
        <span>or press </span>
        <kbd>⌘</kbd>
        <kbd>K</kbd>
      </p>
    </section>

    <section>
      <h2>Recent activity</h2>
      <p v-if="log.length === 0" class="muted">Select a command — activity will appear here.</p>
      <ul v-else class="log">
        <li v-for="line in log" :key="line">{{ line }}</li>
      </ul>
    </section>

    <CommandDialog v-model:open="open" label="Global command menu" loop>
      <CommandInput placeholder="What do you want to do?" />
      <CommandList>
        <CommandEmpty>No matching command.</CommandEmpty>

        <CommandGroup heading="Navigation">
          <CommandItem
            v-for="action in navigation"
            :key="action.value"
            :value="action.value"
            :keywords="action.keywords"
            @select="run"
          >
            <span>{{ action.label }}</span>
            <span v-if="action.hint" class="hint-mono">{{ action.hint }}</span>
          </CommandItem>
        </CommandGroup>

        <CommandSeparator />

        <CommandGroup heading="Actions">
          <CommandItem
            v-for="action in actions"
            :key="action.value"
            :value="action.value"
            :keywords="action.keywords"
            @select="run"
          >
            <span>{{ action.label }}</span>
            <span v-if="action.hint" class="hint-mono">{{ action.hint }}</span>
          </CommandItem>
        </CommandGroup>

        <CommandSeparator />

        <CommandGroup heading="Account">
          <CommandItem
            v-for="action in account"
            :key="action.value"
            :value="action.value"
            :keywords="action.keywords"
            @select="run"
          >
            {{ action.label }}
          </CommandItem>
        </CommandGroup>
      </CommandList>
    </CommandDialog>
  </div>
</template>
